### PR TITLE
Update `library` subtree

### PR DESCRIPTION
**Pull request by carolynzech**
Run the scripts from #46 to update our subtree of `library`. This update is necessary because Kani v0.5.4 uses a more recent version of the Rust compiler, so our subtree of `library` no longer compiles (for those interested, the compilation errors are below).

```
error: the trait `ConstParamTy` may not be implemented for this type
   --> /Users/cmzech/verify-std/library/core/src/marker.rs:998:9
    |
998 |         str /* Technically requires `[u8]: ConstParamTy` */,
    |         ^^^ type is not `Sized`

error: the trait `ConstParamTy` may not be implemented for this type
    --> /Users/cmzech/verify-std/library/core/src/marker.rs:1001:27
     |
1001 |         {T: ConstParamTy} [T],
     |                           ^^^ type is not `Sized`

error: the trait `ConstParamTy` may not be implemented for this type
    --> /Users/cmzech/verify-std/library/core/src/marker.rs:1002:36
     |
1002 |         {T: ?Sized + ConstParamTy} &T,
     |                                    ^^ type is not `Sized`

error: aborting due to 3 previous errors
```
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

**Comment by carolynzech** [comment]
Note that CI for this PR currently fails because the scripts still use the unstable `ptr-to-ref-cast-checks` option, which has since [been stabilized](https://github.com/model-checking/kani/pull/3426). I am working on another PR to update the scripts from #46, which should fix the issue.

**Review by jaisnan — CHANGES_REQUESTED** [review]
Blocking PR to prevent merge via github UI

**Comment by celinval** [comment]
> Note that CI for this PR currently fails because the scripts still use the unstable `ptr-to-ref-cast-checks` option, which has since [been stabilized](https://github.com/model-checking/kani/pull/3426). I am working on another PR to update the scripts from #46, which should fix the issue.

Is the fix a one liner? I'm assuming we need to remove the option from here:

https://github.com/model-checking/verify-rust-std/blob/ec6d98ed385dbcdc62c1eba7643c099f13836341/scripts/check_kani.sh#L47

If so, I would prefer if you add a separate commit here that fixes the issue, and we ensure the regression passes before pushing this. Thanks!

**Comment by carolynzech** [comment]
> If so, I would prefer if you add a separate commit here that fixes the issue, and we ensure the regression passes before pushing this. Thanks!

Yes, you're correct that is the fix. I'm not sure I can add a separate commit here--when I try to push to this branch, I get:

```
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/sync-2024-08-07.
remote: error: Changes must be made through a pull request. 3 of 3 required status checks are expected.
To github.com:model-checking/verify-rust-std.git
 ! [remote rejected]         sync-2024-08-07 -> sync-2024-08-07 (protected branch hook declined)
error: failed to push some refs to 'github.com:model-checking/verify-rust-std.git'
```
I made a PR (#50) to merge into this branch, we can approve that, and then that should retrigger CI.

In the future, we may want to revise the scripts from #46 to setup the remote to point to the user's local fork of this repository (rather than the repository directly) so that we don't have these branch protection issues.

**Comment by carolynzech** [comment]
Replaced with #54

**Pull request closed without merging**
