### PR TITLE
Simplify pr workflow to require 2 approvals on all PR's

### PR DESCRIPTION
**Pull request by jaisnan**
Simplify pr workflow to require 2 approvals on all PR's

## Call Outs
All PR's will need 2 approvals from the commitee for this check to pass. 
A more intelligent approach is on the way, but till then all PR's will need 2 approvals.

This is done to prevent sneak attacks where someone gets approval for non-std related changes, and after approval, they make changes to the std files.

## Testing

Failed check after just 1 approver :- https://github.com/jaisnan/rust-dev/actions/runs/10583003063
Successful check after 2nd approver :- https://github.com/jaisnan/rust-dev/actions/runs/10583018556

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

**Review by carolynzech — APPROVED** [review]
You could comment this out instead of deleting if you think you'll iterate on it later, but up to you.

**Comment by jaisnan** [comment]
> You could comment this out instead of deleting if you think you'll iterate on it later, but up to you.

What do you mean by "this" in "comment this out"?

**Comment by carolynzech** [comment]
> > You could comment this out instead of deleting if you think you'll iterate on it later, but up to you.
> 
> What do you mean by "this" in "comment this out"? If youre talking about the closed PR, then I prefer to start afresh. I need a fresh testing ground for the checks.
I meant comment out the sections of the files you deleted in this PR.

**Comment by jaisnan** [comment]
> > > You could comment this out instead of deleting if you think you'll iterate on it later, but up to you.
> > 
> > 
> > What do you mean by "this" in "comment this out"? If youre talking about the closed PR, then I prefer to start afresh. I need a fresh testing ground for the checks.
> > I meant comment out the sections of the files you deleted in this PR.

Ah sorry. I think I prefer to delete, I can always refer to this PR in case I want to come back to these diffs, and I stashed these changes in my fork too. No reason to keep this branch full of redundant comments.

**Review by tautschnig — APPROVED** [review]

**Pull request merged**
