### PR TITLE
added harnesses for c_str: is_empty

### PR DESCRIPTION
**Pull request by lanfeima**
### Update: 

I noticed that PR #194 leverages `arbitrary_cstr `(introduced in #189) to simplify the harness `CStr::is_empty`. Please also check that PR for additional context.
------------------------------------------------------------------------------------------------------------------

### Parent branch: main

---

### Changes

- added harnesses. for CStr:: is_empty 

This version of C

To revalidate the verification results, run `./scripts/run-kani.sh --kani-args --harness ffi::c_str::verify::check_is_empty` 

Example output: 
```bash
Checking harness ffi::c_str::verify::check_is_empty...

VERIFICATION RESULT:
 ** 0 of 216 failed (5 unreachable)

VERIFICATION:- SUCCESSFUL
Verification Time: 1121.6111s

Complete - 1 successfully verified harnesses, 0 failures, 1 total.
```

### CODE REVIEW

**Comment by Yenyun035** [comment]
Duplicate with #194. Will resolve later.

**Comment by lanfeima** [comment]
I see that PR #194 takes an efficient approach by leveraging arbitrary_cstr. The main difference is that PR #195 explores handling invalid cases during the construction phase (e.g., how is_empty behaves under invalid input), which might not be necessary given that is_empty can only be invoked on valid CStr instances. I now realize that focusing on valid inputs may be more aligned with the project goals.

Would it make sense to address invalid cases elsewhere, or should we focus solely on valid instances here? Feedback from reviewers would be helpful. I’d be happy to close this PR or contribute to refining #194 to include any missing edge cases if needed. Thank you!

**Comment by celinval** [comment]
Can we merge the ideas by optimizing the `arbitrary_str` by adding byte 0 to the end of the slice?

**Comment by tautschnig** [comment]
Closing per https://github.com/model-checking/verify-rust-std/pull/195#issuecomment-2510283149.

**Pull request closed without merging**
