### PR TITLE
Fix challenges numbering

### PR DESCRIPTION
**Pull request by feliperodri**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

**Review by jaisnan — APPROVED** [review]
Thanks!

**Review by carolynzech — COMMENTED** [review]
I find the blank page with -- to be a bit odd -- should we just wait until we have another challenge to be challenge 7? The challenges still go 6 -> 8 visually.

**Comment by feliperodri** [comment]
> I find the blank page with -- to be a bit odd -- should we just wait until we have another challenge to be challenge 7?

@carolynzech when I texted locally, this would lead to the wrong numbering of the challenges until we add the challenge 7 (the sequence didn't obey the numbering order when rendered). Am I missing something? If so, I can remove the blank page. If not, I'm ok with keeping it until we include a new challenge next week.

**Comment by jaisnan** [comment]
> > I find the blank page with -- to be a bit odd -- should we just wait until we have another challenge to be challenge 7?
> 
> @carolynzech when I texted locally, this would lead to the wrong numbering of the challenges until we add the challenge 7 (the sequence didn't obey the numbering order when rendered). Am I missing something? If so, I can remove the blank page. If not, I'm ok with keeping it until we include a new challenge next week.

Fwiw, i'm okay with the blank page until next week as well. Your concern is valid, but this should be fixed shortly when we add our challenge.

**Comment by celinval** [comment]
@feliperodri you could also enable your fork to publish documentation from your `fix-numbers` branch so we can review how it looks like.

> I find the blank page with -- to be a bit odd -- should we just wait until we have another challenge to be challenge 7? The challenges still go 6 -> 8 visually. I like the changes to make the links to issues consistent. I was planning to write another challenge sometime next week, so I would propose that we avoid making this blank file and instead just wait for that to be challenge 7.

Which blank page are we talking about?

**Comment by feliperodri** [comment]
> @feliperodri you could also enable your fork to publish documentation from your `fix-numbers` branch so we can review how it looks like.

@celinval I'll enable it. Meanwhile, here it's an imagine:
Screenshot 2024-09-06 at 5 42 49 PM

> Which blank page are we talking about?

I already removed it. I added an unnecessary blank page.

**Review by carolynzech — APPROVED** [review]

**Comment by feliperodri** [comment]
@celinval I think I need one more approval to get it merge.

**Comment by carolynzech** [comment]
> @celinval I think I need one more approval to get it merge.

Hm, two approvals should be enough--seems like the check approval action is hanging. I'm going to try revoking my approval and then re-approving to see if that triggers the check.

**Review by carolynzech — APPROVED** [review]

**Pull request merged**
