### PR TITLE
Harness for `CStr::is_empty`

### PR DESCRIPTION
**Pull request by Yenyun035**
Towards #150 
Depends on #189 (merged)

### Changes
* Added a harness for `is_empty`
* Added a small optimization for `arbitray_cstr`

### Verification Result
```
SUMMARY:
 ** 0 of 193 failed (5 unreachable)

VERIFICATION:- SUCCESSFUL
Verification Time: 51.462265s

Complete - 1 successfully verified harnesses, 0 failures, 1 total.
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

**Comment by tautschnig** [comment]
I believe this requires #189 to be merged first.

**Comment by Yenyun035** [comment]
Yes.

**Comment by Yenyun035** [comment]
#189 has been merged.

**Review by celinval — APPROVED** [review]
Thanks

**Review by tautschnig — APPROVED** [review]

**Pull request merged**
